#  Consume: <consume>
#  KeyLore: <keylore>
#  Command:
#    OP:
#    - "<command_op_1>"
#    - "<command_op_2>"
#    Console:
#    - "<command_console_1>"
#    - "<command_console_2>"
Suicide:
  Consume: true
  KeyLore: Suicide
  Command:
    OP:
    - suicide
Confirm:
  Consume: false
  KeyLore: Xác minh
  Command:
    Console:
    - lp user {player} permission set warden.2
    OP:
    - unbreaking true
Buff:
  Consume: true
  KeyLore: Give all buff for 1 minutes
  Command:
    Console:
    - effect {player} 1 60 2
    - effect {player} 3 60 1
    - effect {player} 5 60 1
    - effect {player} 8 60 2
    - effect {player} 10 60 2
Inferno:
  Consume: false
  KeyLore: '&cHoả Ngục'
  Command:
    Op:
    - papi parse me %javascript_light-skill%
Ruthless_1:
  Consume: false
  KeyLore: '&eVô Tâm I'
  Command:
    Op:
    - papi parse me %javascript_lucifer-scythe_1%
Ruthless_2:
  Consume: false
  KeyLore: '&eVô Tâm II'
  Command:
    Op:
    - papi parse me %javascript_lucifer-scythe_2%
Ruthless_3:
  Consume: false
  KeyLore: '&eVô Tâm III'
  Command:
    Op:
    - papi parse me %javascript_lucifer-scythe_3%
Dark-Energy:
  Consume: false
  KeyLore: '&5Năng lượng tối'
  Command:
    Op:
    - papi parse me %javascript_dark-energy%
Superior-Build:
  Consume: false
  KeyLore: '&bXử lí khối'
  Command:
    Console:
    - papi parse {player} %javascript_superior_build%
Auto-Build:
  Consume: false
  KeyLore: '&6Điều khiển kho'
  Command:
    Console:
    - papi parse {player} %javascript_ap_skill%
